[build-system]
requires = ["setuptools ~= 58.0"]

[project]
name = "komoe-sass"
description = "Sass plugin for Komoe"
authors = [{name = "Louis DEVIE"}]
dynamic = ["version"]

[project.urls]
Home = "https://github.com/louisdevie/komoe-sass"